### ISSUE TITLE
Add code for automating derivation of FBdv slice for lethal phase [sf#1]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/flybase-controlled-vocabulary#1]
@dosumis 
**Reported by djs93 on 2013-05-09 14:38 UTC**
Spec: For `life stage` get EquivalentClass, Ancestors, Descendants.  Get descendants for `developmental stage' that part_of some 'immature adult stage'`.

For now, this is generated using an [OBO-Edit filtered save](https://sourceforge.net/p/fbcv/code-0/HEAD/tree/src/trunk/ontologies/imports/FBdv_life_stage_export_filter.xml), but this should be replaced by an OWL-API based pipeline script.

**Comment by dosumis** [comment]
Wow this is really ancient.   Not a VFB concern - but fixing could be justified under Monarch.  A robot extract is probably sufficient. I've put this under an epic for modernising FBcv repo.

**Comment by dosumis** [comment]
Fixed by ODK move
