### ISSUE TITLE
Rewrite auto_def_sub.pl in scala so that it works for all OWL files

### ISSUE THREAD

**Issue by temjones** [FlyBase/flybase-controlled-vocabulary#11]
DOS noticed this in OLS:

<img width="1174" alt="screen shot 2017-11-21 at 13 37 31" src="https://user-images.githubusercontent.com/22234198/33075397-383765fc-cec1-11e7-9859-28d6885390c4.png">

**Comment by Clare72** [comment]
fixed by Nico's update to autodef generation
