### ISSUE TITLE
Use of wrong created by relation?

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#118]
ttp://www.geneontology.org/formats/oboInOwl#created_by

https://www.ebi.ac.uk/ols/ontologies/dpo/properties?iri=ttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23created_by

**Comment by Clare72** [comment]
@matentzn what is the 'correct' created_by property?
I think we use http://www.geneontology.org/formats/oboInOwl#created_by across all the FlyBase ontologies

**Comment by matentzn** [comment]
yes but look at the first letter in the example I gave! Missing `h`!

**Comment by Clare72** [comment]
I see. Looks like the incorrect one is only on CARO:0020003 'cellular anatomical structure' - imported into dpo. Nothing else in FBcv or dpo.

**Comment by matentzn** [comment]
Ahh ok! Well, close it then! Not your problem. Another reason do push https://github.com/obophenotype/caro/issues/22 

you can close this here then..
