### ISSUE TITLE
3 FBcv terms are missing 'phenotypic_class' namespace

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#120]
The following FBcv terms are under 'phenotype' but are missing the 'phenotypic_class' namespace. This means that they are not loading up into Canto properly (as its presumably using the namespace to 'find' all the phenotypic class terms).

I don't know whether any of the other recently created pheno class terms have a similar issue, but please could the following line be added to these three terms and any others where it is missing:

namespace: phenotypic_class

[Term]
id: FBcv:0007504
name: abnormal body weight
def: "Phenotype that is any abnormality in body weight compared to identically raised wild-type controls." [FBC:CP]
is_a: FBcv:0001347 ! phenotype
created_by: http://orcid.org/0000-0002-1373-1705
creation_date: 2020-12-15T15:47:07Z

[Term]
id: FBcv:0007505
name: increased body weight
def: "Phenotype that is an increase in body weight compared to identically raised wild-type controls." [FBC:CP]
is_a: FBcv:0001347 ! phenotype
created_by: http://orcid.org/0000-0002-1373-1705
creation_date: 2020-12-15T15:50:18Z

[Term]
id: FBcv:0007506
name: decreased body weight
def: "Phenotype that is a decrease in body weight compared to identically raised wild-type controls." [FBC:CP]
is_a: FBcv:0001347 ! phenotype
created_by: http://orcid.org/0000-0002-1373-1705
creation_date: 2020-12-15T15:50:44Z

**Comment by Clare72** [comment]
Sorry about that, looks like I forgot to add phenotypic_class to just those three - I checked all the other new phenotype terms I made and they have the namespace.
I have corrected this in dpo-edit.obo and it will be fixed next release.
Can you add `namespace: phenotypic_class` (below `name` field) to these terms manually in the file that canto is reading?

**Comment by gm119** [comment]
>  Can you add namespace: phenotypic_class (below name field) to these terms manually in the file that canto is reading?
 yes, that is a good idea, will do that and send updated version to Kim
