### ISSUE TITLE
NTR: beta particle

### ISSUE THREAD

**Issue by sjm41** [FlyBase/flybase-controlled-vocabulary#134]
## Preferred term label
beta ray

## Synonyms
beta radiation
beta particle

## Textual definition
A beta ray is a high-energy, high-speed electron or positron emitted by the radioactive decay of an atomic nucleus during the process of beta decay. (https://en.wikipedia.org/wiki/Beta_particle)

## Suggested parent term
ionizing radiation (FBcv:0000504)

## Other notes
Once this term is created, these terms should be moved to be children of it:
- 3H (FBcv:0000511)
- 3H-deoxycytidine (FBcv:0000512)
- 3H-thymidine (FBcv:0000513)
- 32P (FBcv:0000510)
(see https://en.wikipedia.org/wiki/Tritium & https://en.wikipedia.org/wiki/Phosphorus-32)

**Comment by sjm41** [comment]
Based on discussion in #135, we can probably forget about this request - will close once #135 is finalised.

**Comment by Clare72** [comment]
@sjm41 - can I close this now or is there still something needed?

**Comment by sjm41** [comment]
I guess we can close...
