### ISSUE TITLE
New terms for annotating scRNAseq datasets

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/flybase-controlled-vocabulary#138]
We'll need a few new terms to properly annotate scRNAseq datasets.

At the very least, we'll need:

* under `assay type` (FBcv:00003050): one term for "single-cell RNA-Seq" and one for "single-nucleus RNA-Seq";
* under `result type` (FBcv:00003082): one term for "cell clustering analysis" and one for "cell cluster" (may want a better label for that one);
* under `biosample type` (FBcv:00003044): one term for "isolated nuclei", similar to the `isolated cells` we already have (FBcv:00003047).

We may also want new terms under `assay method` (FBcv:00003208) for the scRNAseq platform used (e.g., 10⨉ Genomics or Smart-Seq2), similar to `Affymetrix Gene Expression Array {1,2}`.

**Comment by dosumis** [comment]
Consider making mappings to EFO & OBI for these.  Could use [SSSOM](https://github.com/mapping-commons/SSSOM) to record.  @matentzn - Is there a mapping commons we could use to deposit these?  Might be better for keeping track if they live on the FBcv repo.

**Comment by matentzn** [comment]
great thinking @dosumis I was thinking the same and didn't dare to say. 

No mapping commons for this yet; for now, just xrefs -> I have tools to turn these into sssom files and I will get all the ontologies to do that once they toolkits are mature.

Also, if no OBI term exists, maybe good idea to request one.

**Comment by gouttegd** [comment]
Good point, I'll check EFO and OBI and see if they already have terms we could map to (or suggest they add such terms if not).

As for how to represent the mappings, SSSOM is certainly on FlyBase's radar (FlyBase/drosophila-anatomy-developmental-ontology#1207), but there's no plan to start using it right now. If it will be possible to automatically switch from xrefs to SSSOM in the future, that's great.
