### ISSUE TITLE
Misformed PATO iri for FBcv_0006001

### ISSUE THREAD

**Issue by kshefchek** [FlyBase/flybase-controlled-vocabulary#15]
Theres a PATO iri that is part of the FBcv_0006001 axiom that is missing a 'h':

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/FBcv_0006001">
        <owl:equivalentClass>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="ttp://purl.obolibrary.org/obo/PATO_0001695"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0000052"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/FBbt_00000001"/>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
     </owl:equivalentClass>

as well as part of the class definition

    
       <owl:Class rdf:about="ttp://purl.obolibrary.org/obo/PATO_0001695">

**Comment by kshefchek** [comment]
@dosumis I'm running into this issue again, has been pushed to the current release, or is it possible this reverted? See https://github.com/monarch-initiative/monarch-owlsim-data/issues/5

**Comment by dosumis** [comment]
Hmm - seems like we haven't run a release in a year!  @Clare72  - can  you run one (&  ping me if you have problems)?
