### ISSUE TITLE
NTR: starvation (biosample attribute)

### ISSUE THREAD

**Issue by gouttegd** [FlyBase/flybase-controlled-vocabulary#153]
We need a new term under `biosample attribute` (FBcv:0003137) to represent samples obtained from larvae or adult flies that were starved before being collected.

Label: “starvation”

Parent class: `growth condition` (FBcv:0003146)

Definition: “A sample in which individuals have been deprived of food.”

**Comment by dosumis** [comment]
Is this connected to scAtlas work?  If so we should probably think about mapping to some more general ontology and look at how we can fold into the scao build.

**Comment by gouttegd** [comment]
No, this is for internal use at FlyBase. All datasets “objects” (biosamples, assays, results) are described using FBcv terms under `dataset attribute` [FBcv:0003121](http://purl.obolibrary.org/obo/FBcv_0003121).

**Comment by Clare72** [comment]
We could probably map a lot of stuff under 'dataset descriptor' to other ontologies, this should have its own ticket if you think it's worth doing.
