### ISSUE TITLE
new conditional gene product localization term(s)

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#162]
We've got a new tool (LEXY, used in FBrf0253050, original description in PMID:26853913) that acts a a light-regulated nuclear export signal. We don't currently have any 'conditional' FBcv terms under 'gene product localization tag' (FBcv:0005022). 

I can see two possible options, described below.

I think OPTION 1. is probably more similar to what we've done for other conditional experimental tool terms, so I guess we should probably go with that for consistency, but would be good to get the ontologists take on this.

**OPTION 1.**

Make conditional terms as needed as children of the specific localization tag terms, so in this case for LEXY, if we go for this option, one new term would be needed:

[Term]
id: FBcv:NEW
name: light-regulated nuclear export signal
namespace: experimental_tool_descriptor
def: "A peptide sequence used to target a tagged protein for export from the nucleus to the cytoplasm, where this property can be regulated by irradiation with a pulse of light." [FBC:GM]
is_a: FBcv:0005035 ! nuclear export signal

**OPTION 2.**

Rather than make conditional terms for each specific localization tag (NES, NLS, signal sequence etc.) as we need them,  we could instead have a 'high level' set of conditional terms directly under gene product localization tag, as follows:

[Term]
id: FBcv:NEW
name: conditional gene product localization tag
namespace: experimental_tool_descriptor
def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which is used to target the tagged gene product either to a specific subcellular location within the cell or for secretion to the extracellular space, where this property can be regulated in response to a particular stimulus." [FBC:GM]
is_a: FBcv:0005022 ! gene product localization tag

[Term]
id: FBcv:NEW
name: light-regulated gene product localization tag
namespace: experimental_tool_descriptor
def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which is used to target the tagged gene product either to a specific subcellular location within the cell or for secretion to the extracellular space, where this property can be regulated by irradiation with a pulse of light." [FBC:GM]
is_a: FBcv:NEW ! conditional gene product localization tag

[Term]
id: FBcv:NEW
name: small molecule-regulated gene product localization tag
namespace: experimental_tool_descriptor
def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which is used to target the tagged gene product either to a specific subcellular location within the cell or for secretion to the extracellular space, where this property can be regulated by binding to a small molecule, such as an ion or ligand." [FBC:GM]
is_a: FBcv:NEW ! conditional gene product localization tag

then for conditional tags such as LEXY, we could just annotate them with the relevant conditional term plus whatever specific localization tag is appropriate (for LEXY, it would be 'light-regulated gene product localization tag' AND 'nuclear export signal').

**Comment by Clare72** [comment]
Happy to do whatever you think will be most useful. We could even go higher level and make 'conditional experimental tool' etc. Is it easy for users to search for an intersection of terms in this way? If not we should probably keep making the specific terms (perhaps in addition to higher level conditional terms).

**Comment by gm119** [comment]
> Is it easy for users to search for an intersection of terms in this way?
good point, not that easy at the moment I think.
So can we go for option 1 for now and just make the specific 'light-regulated nuclear export signal' term

(In the future we may want to revisit your suggestion of making really high level 'conditional experimental tool' etc, but for now I think adding the specific terms is the simplest and will make it easiest for the users to search at the moment)
