### ISSUE TITLE
PATO_0001695 wrong url format

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#18]
During PATO mapping, the PATO_0001695 IRI was somehow broken. If you check fbcv.owl, and search for 

ttp://purl.obolibrary.org/obo/PATO_0001695

you can see that for some reason, the "h" in the beginning of the URL is missing. This can cause problems with mapping this ontology to others in the long run.

**Comment by matentzn** [comment]
(I checked the PATO release and the "h" is there)

**Comment by matentzn** [comment]
Was this fixed?

**Comment by dosumis** [comment]
We should aim to run a release before refactoring the repo.
