### ISSUE TITLE
tweaks to gene product degradation tag section of FBcv

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#191]
Please could the following tweaks be made to the 'gene product degradation tag' section of FBcv.

**1. definition tweak**

id: FBcv:0005042
name: gene product degradation tag

_current definition:_

def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which results in the tagged gene product being targeted for degradation, where this property can be regulated by a specific process or entity." [FBC:GM]

_new definition:_

def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which results in the tagged gene product being targeted for degradation." [FBC:GM]

(this parent term is not intended to be conditional, and the "where this property can be regulated by a specific process or entity" part of the definition snuck in as part of #109 in error as I wasn't completely clear in that ticket).

**2. new term for general conditionality**

[Term]
id: FBcv:NEW
name: conditional gene product degradation tag
namespace: experimental_tool_descriptor
def: "Sequence that forms part of the gene product encoded by a transgenic locus or modified endogenous locus and which results in the tagged gene product being targeted for degradation, where this property can be regulated in response to a particular stimulus." [FBC:GM]
is_a: FBcv:0005042 ! gene product degradation tag

**3. change immediate parent of existing conditional terms to be the new term made in 2.**

for each of the three terms listed below, the is_a parent should be changed to be the 'conditional gene product degradation tag' term.

terms:

id: FBcv:0007047
name: light-regulated gene product degradation tag

id: FBcv:0005043
name: cell cycle-regulated gene product degradation tag

id: FBcv:0005083
name: small molecule-regulated gene product degradation tag

change:

is_a: FBcv:0005042 ! gene product degradation tag

to

is_a: FBcv:NEW ! conditional gene product degradation tag

**Comment by gouttegd** [comment]
My bad, I had not included the namespace when I added the term, so it was in the default "FlyBase miscellaneous CV" namespace.

It’s fixed now. Do you want me to schedule an emergency release and a FBcv update in Chado ASAP? Or is it okay to wait for the next normal update? (FBcv had just been updated in Chado earlier this month, so I was not planning another update for the next 3 months or so.)

**Comment by gm119** [comment]
I think its fine to wait - I will make sure I check that the Vocabularies page etc. looks OK for the upcoming FB release - if it does break things we might have to do a patch, but hopefully it wont

**Comment by gouttegd** [comment]
OK. I’ll keep this ticket open for now, until we can confirm that everything is fine when the next FB release happens.

**Comment by gouttegd** [comment]
Thanks for checking!
