### ISSUE TITLE
PURL to DPO does not resolve properly

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#21]
https://purl.obolibrary.org/obo/dpo.owl
https://purl.obolibrary.org/obo/dpo

exist as per 

http://obofoundry.org/ontology/dpo.html

but does not resolve. Can we redirect for example to: 

https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/dpo-non-classified.owl

**Comment by dosumis** [comment]
Pattern is slightly different: 

http://purl.obolibrary.org/obo/fbcv/dpo.owl

The link here is correct:

![image](https://user-images.githubusercontent.com/112839/42576019-75535d1a-8519-11e8-8343-13c54492fbb0.png)

But PURL is wrong here: 
![image](https://user-images.githubusercontent.com/112839/42576099-912bd760-8519-11e8-9d72-05e559591032.png)

This page is driven by:

https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/dpo.md

Unfortunately the PURL seems to be derived, not directly asserted.

I've attempted to correct in this pull request:

https://github.com/OBOFoundry/OBOFoundry.github.io/compare/master...dosumis:patch-2

But perhaps better to just request the dpo PURL from the foundry, which would allow us to have a more conventional obo purl.

**Comment by dosumis** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/665

**Comment by matentzn** [comment]
Thanks David.

**Comment by Clare72** [comment]
Looks like this is fixed - closing
