### ISSUE TITLE
Edits to 'pathway group' FBcv terms

### ISSUE THREAD

**Issue by sjm41** [FlyBase/flybase-controlled-vocabulary#219]
Hi @Clare72 

1. Change name of FBcv:0003017 from 'pathway group' to 'signaling pathway group'.

2. Change def of FBcv:0003017 to 'Genes whose products act in a specified signal transduction pathway.'

3. Make new term as follows:
name: 'metabolic pathway group'
def: 'Genes whose products act in a specified metabolic pathway.'
parent: functional group (FBcv:0003014)

Thanks!
Steven

**Comment by Clare72** [comment]
Hi Steven, rather than narrowing the 'pathway group' term, I think I would be more comfortable making two new subclasses for signaling and metabolic pathways as subclasses of 'pathway group'. Would that be okay with you?

**Comment by hattrill** [comment]
@sjm41 I am ok with that. There are some pipelines at Harv and IU that use the pathway cv, so after the update will have to make sure that they have made the necessary changes - but I would have had to have checked with them for the name change anyway, so not a biggie.

**Comment by sjm41** [comment]
Hi Clare I am also OK with your proposal, and that approach would indeed be more 'ontologically correct'.

But what I failed to say in my first comment was that all 71 uses of "FBcv:0003017 pathway group" to date have been exclusively for "signaling pathways", meaning that my original suggestion would be accurate and easy, and avoid us having to change the CV term annotated to those 71 current groups.
But that's not a big objection/task, and I'm happy with your alternative!

**Comment by Clare72** [comment]
I have gone with creating new subclasses, so we will still have 'pathway group' to group the different pathways as well as the more specific terms.

**Comment by sjm41** [comment]
Thanks Clare.

@hattrill - we hope to get these changes into FB2024_03, so that would be the time to change the CV on the existing signalling pathway groups to the new term and coordinate this with any changes required by Harvdev/IU. (So nothing to do here for the upcoming FB2024_02 release)
