### ISSUE TITLE
two new tool terms: children of reporter enzyme

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#221]
I think it would be good to add two new terms under the current 'reporter enzyme' term, so that users can easily distinguish reporters that use 'chemical tagging' (e.g. SNAP-tag, Halo-tag) or result in bioluminesence (e.g. luciferase).

here are my suggestions for the two new terms:

[Term]
id: FBcv:NEW
name: chemical labeling reporter
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the protein product encoded by a transgenic locus or modified endogenous locus and that encodes an enzyme whose activity results in covalent tagging of the protein product with a small molecule whose properties (typically fluorescence) can be used to detect the presence of that protein product." [FBC:GM]
subset: common_tool_use
is_a: FBcv:0005005 ! reporter enzyme

[Term]
id: FBcv:NEW
name: bioluminescence reporter
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the protein product encoded by a transgenic locus or modified endogenous locus and that encodes an enzyme whose activity results in bioluminescence, which can be used to detect the presence of that protein product." [FBC:GM]
subset: common_tool_use
is_a: FBcv:0005005 ! reporter enzyme

**Comment by aoifelarkin** [comment]
This seems like a good idea and the descriptions look clear to me. Should be useful for users.
