### ISSUE TITLE
Update terms imported from ChEBI

### ISSUE THREAD

**Issue by althonos** [FlyBase/flybase-controlled-vocabulary#25]
Hi !

The latest release of `fbcv` contains syntax errors in the terms imported from ChEBI that have since then been fixed upstream, but the changes have not been propagated to `fbcv-edit.obo` (e.g. 
```
synonym: "Actinomycin" EXACT [KEGG COMPOUND:]
``` 
has changed to
```
synonym: "Actinomycin" EXACT [KEGG_COMPOUND]
```
which is correct OBO 1.4 syntax)

**Comment by dosumis** [comment]
HI @althonos - thanks for reporting. We are in the process of rebuilding our pipeline (using ODK) and are planning a new release soon.   If this  is a blocker for any of  your  work, we could consider a minor update that patches the release files.

**Comment by althonos** [comment]
Hi ! Indeed using the ODK should fix this issue. I am using the OBO foundry as a test suite for my parser implementation for the OBO 1.4 format, so I can just comment this test out; but since the required changes are minimal, I would be glad if you could patch them instead!

**Comment by Clare72** [comment]
This should be fixed now we are using ODK - example given (actinomycin) is fixed

**Comment by althonos** [comment]
Indeed, thanks!
