### ISSUE TITLE
neuron activity regulation tool terms

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#27]
New terms to use with experimental tools that regulate neuron activity, to go under 'experimental tool descriptor' branch of FBcv

**A. summary of tree:**

	neuron activity regulation tool

		neuron inhibition tool
			conditional neuron inhibition tool
				light-regulated neuron inhibition tool
				small molecule-regulated neuron inhibition tool
				temperature-regulated neuron inhibition tool
		neuron activation tool
			conditional neuron activation tool
				temperature-regulated neuron activation tool
				small molecule-regulated neuron activation tool
				light-regulated neuron activation tool

**B. New CV terms  requested:**

(have put FBcv:NEW as a place-holder where one of the terms has a relationship to another of the new terms)

name: neuron activity regulation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to regulate the activity of a neuron. This is often achieved by manipulation of membrane potential or synaptic transmission dynamics." [FBC:GM]
synonym: electrically signalling cell activity regulation tool
is_a: FBcv:0005001 ! experimental tool descriptor

name: neuron inhibition tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to inhibit the activity of a neuron. This is often achieved by inducing membrane hyperpolarization (GO:0060081)." [FBC:GM]
synonym: electrically signalling cell inhibition tool
is_a: FBcv:NEW ! neuron activity regulation tool

name: conditional neuron inhibition tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to inhibit the activity of a neuron, where this property can be regulated in response to a particular stimulus." [FBC:GM]
is_a: FBcv:NEW ! neuron inhibition tool

name: light-regulated neuron inhibition tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to inhibit the activity of a neuron, where this property can be regulated by irradiation with a pulse of light." [FBC"GM]
synonym: optogenetic neuron inhibition tool
is_a: FBcv:NEW ! conditional neuron inhibition tool

name: small molecule-regulated neuron inhibition tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to inhibit the activity of a neuron, where this property can be regulated by binding to a small molecule, such as an ion or ligand." [FBC:GM]
is_a: FBcv:NEW ! conditional neuron inhibition tool

name: temperature-regulated neuron inhibition tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to inhibit the activity of a neuron, where this property can be regulated by temperature." [FBC:GM]
is_a: FBcv:NEW ! conditional neuron inhibition tool

name: neuron activation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to stimulate the activity of a neuron. This is often achieved by inducing membrane depolarization (GO:0051899)." [FBC:GM]
synonym: electrically signalling cell activation tool
is_a: FBcv:NEW ! neuron activity regulation tool

name: conditional neuron activation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to stimulate the activity of a neuron, where this property can be regulated in response to a particular stimulus." [FBC:GM]
is_a: FBcv:NEW ! neuron activation tool

name: light-regulated neuron activation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to stimulate the activity of a neuron, where this property can be regulated by irradiation with a pulse of light." [FBC"GM]
synonym: optogenetic neuron activation tool
is_a: FBcv:NEW ! conditional neuron activation tool

name: small molecule-regulated neuron activation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to stimulate the activity of a neuron, where this property can be regulated by binding to a small molecule, such as an ion or ligand." [FBC:GM]
is_a: FBcv:NEW ! conditional neuron activation tool

name: temperature-regulated neuron activation tool
namespace: experimental_tool_descriptor
def: "Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that confers a specific property that can be used to stimulate the activity of a neuron, where this property can be regulated by temperature." [FBC:GM]
is_a: FBcv:NEW ! conditional neuron activation tool

**Comment by Clare72** [comment]
Thermogenetic is the temperature equivalent to optogenetic, so I will add the synonyms:
'thermogenetic neuron inhibition tool'
'thermogenetic neuron activation tool'
to the appropriate terms
