### ISSUE TITLE
new experimental tool sensor terms

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#32]
Term requests for tools that are used as sensors for the **activity** of biological processes/pathway/product, rather than just to detect the presence/absence/localization of a gene product.

NB.

* In each case I wrote 'specified' in the definition, but am not sure whether 'specific' would be better

name: biological process activity sensor
namespace: experimental_tool_descriptor
def: Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that is used to provide a readout of the activity of a specified biological process.
is_a: FBcv:0005044 | genetically encoded sensor
synonym: reporter of biological process pathway activity

example of the above for context:
https://flybase.org/reports/FBal0319233 - sensor for caspase activity (i.e. apoptosis)

name: signal transduction pathway activity sensor
namespace: experimental_tool_descriptor
def: Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that is used to provide a readout of the activity of a specified signal transduction pathway.
synonym: reporter of signal transduction pathway activity
is_a: FBcv:NEW | biological process activity sensor

name: gene product activity sensor
namespace: experimental_tool_descriptor
def: Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that is used to provide a readout of the activation state of a specified gene product.
synonym: gene product activation state detection tool
is_a: FBcv:0005044 | genetically encoded sensor

example of the above for context:
https://flybase.org/reports/FBal0243925 - biosensor for Rac activity

**Comment by Clare72** [comment]
Other tool terms seem to favour 'specific', so I will go with that for consistency.
Examples:

"protein localization tag"
"A peptide sequence that forms part of the protein product encoded by a transgenic locus or modified endogenous locus and which is used to target the tagged protein either to a **specific** subcellular location within the cell or for secretion to the extracellular space."

"photoconvertible fluorescent protein"
"A protein that can be converted from one fluorescent state to another fluorescent state (with a changed emission spectrum peak) by irradiation with a pulse of light of a **specific** wavelength. This conversion is irreversible."
