### ISSUE TITLE
new genome engineering tool terms for RMCE elements

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#33]
I thought it would be nice to have a pair of terms to be able to mark RMCE target and RMCE donor elements, so that researchers can easily find insertions of constructs where new drivers/fluorescent proteins etc, can easily be swapped in and out. I've made a pair of new terms for this, below.

[Term]
name: RMCE target
namespace: experimental_tool_descriptor
def: "An RMCE target element contains a region of DNA sequence flanked by a pair of target sites for a recombinase or an integrase, which are arranged such that this target sequence cassette can be replaced with donor sequence from a compatible RMCE donor element via recombination-mediated cassette exchange (RMCE). For RMCE mediated by a recombinase, the target cassette is flanked by two non-identical recombinase target sites that each carry a different mutation in the spacer sequence of the target site; this renders the two sites incompatible with each other. A compatible RMCE donor cassette is flanked by the same pair of non-identical sites; in the presence of recombinase, a double recombination event between the identical sites on the donor and target sequences results in replacement of the target cassette with the donor cassette. In the case of RMCE mediated by an integrase, the RMCE cassette is flanked by identical integrase target sites, while a compatible RMCE donor cassette is flanked by copies of the orthogonal integrase target site; in the presence of integrase, a double recombination event results in the target cassette being replaced with that of the donor cassette. In this case, if the flanking sites are in inverted orientation, replacement of the target cassette can occur in either direction." [FBC:GM, PMID:7947678, PMID:21445009, FlyBase:FBrf0231034]
is_a: FBcv:0005075 ! genome engineering tool
synonym: recombination-mediated cassette exchange target element

[Term]
name: RMCE donor
namespace: experimental_tool_descriptor
def: "An RMCE donor element contains a region of DNA sequence flanked by a pair of target sites for a recombinase or an integrase, which are arranged such that this donor sequence cassette can be used to replace target sequence of a compatible RMCE target element via recombination-mediated cassette exchange (RMCE). For RMCE mediated by a recombinase, the target cassette is flanked by two non-identical recombinase target sites that each carry a different mutation in the spacer sequence of the target site; this renders the two sites incompatible with each other. A compatible RMCE donor cassette is flanked by the same pair of non-identical sites; in the presence of recombinase, a double recombination event between the identical sites on the donor and target sequences results in replacement of the target cassette with the donor cassette. In the case of RMCE mediated by an integrase, the RMCE cassette is flanked by identical integrase target sites, while a compatible RMCE donor cassette is flanked by copies of the orthogonal integrase target site; in the presence of integrase, a double recombination event results in the target cassette being replaced with that of the donor cassette. In this case, if the flanking sites are in inverted orientation, replacement of the target cassette can occur in either direction." [FBC:GM, PMID:7947678, PMID:21445009, FlyBase:FBrf0231034]
is_a: FBcv:0005075 ! genome engineering tool
synonym: recombination-mediated cassette exchange donor element

**Examples of each type:**

**1. RMCE target**

Mi{MIC}	https://flybase.org/reports/FBtp0051711
P{loxP-y-lox511}	https://flybase.org/reports/FBtp0082282
PBac{806.LOX-SVS-2}	https://flybase.org/reports/FBtp0065988

**2. RMCE donor**

P{FRT(PT-GFSTF.0)}	https://flybase.org/reports/FBtp0108915
P{lox(Trojan-GAL4)x3}	https://flybase.org/reports/FBtp0099339

pBS-KS-attB1-2-GT-SA-Flpo-SV40	https://flybase.org/reports/FBmc0003060
pBS-KS-attB1-2-GT-SA-GAL4-Hsp70pA	https://flybase.org/reports/FBmc0003059

**Questions:**

- are these two terms enough, or should we perhaps also (or instead) have a more general 'swappable cassette' term, in case there are elements that have a swappable cassette that can be replaced by some other non-RMCE mechanism

- should the terms also be listed as children of insertional mutagenesis tool ?

**Comment by Clare72** [comment]
I think these are the right level of specificity. If we need another mechanism, we should probably make another term. We might also want a term to describe tools used for homologous recombination e.g. pTV[cherry] (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3833436/), but I think this is different enough to RCME that we shouldn't try to lump them together as 'swappable cassette'.

No, I don't think they should fall under 'insertional mutagenesis tool' as they may not always be 'designed to impact or assess any proximate gene(s) when integrated into the genome'.

**Comment by Clare72** [comment]
Perhaps we could add 'element' to these names too to match 'docking element' (you have already done this in the definitions).

**Comment by gm119** [comment]
I think adding 'element' to these two term names would be fine (they'll still be fairly short, which is good)
