### ISSUE TITLE
docking site tool term

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#34]
New term to make it easy for researchers to find all available docking site insertions

[Term]
name: docking site
namespace: experimental_tool_descriptor
def: "A docking site is an element that has been introduced into a site in the genome to allow integration of DNA at a defined location; this neutralizes the problem of position effects that are seen with non-specific insertion techniques such as transposable-element-mediated transgenesis. A docking site contains a single target site for an integrase, allowing subsequent integration of DNA into this site from a donor element via integrase mediated recombination. The docking site in the genome typically contains the 'attB' site and the donor plasmid contains the 'attP' site, since this directionality gives higher integration rates compared to the alternative combination where the 'attB' site is integrated into the genome. A docking site insertion is typically selected to be 'benign' (that is it does not result in disruption of an endogenous locus) and to show a high rate of integration in the presence of integrase." [FBC:GM, PMID:11359900, PMID:12563279, FlyBase:FBrf0194996, FlyBase:FBrf0192974]
is_a: FBcv:0005075 ! genome engineering tool
synonym: landing site

**Examples**

P{CaryP}	https://flybase.org/reports/FBtp0018807
M{3xP3-RFP.attP}	https://flybase.org/reports/FBtp0021844

**Comment by Clare72** [comment]
Would we want this to cover RMCE target sites in the genome? (see FBrf0231034 Fig 10)
At the moment it does not, if this is what is desired, perhaps we should rename to 'integrase-mediated docking site' or similar and make it a subclass of 'integrase target site'. Otherwise the definition needs expanding.

**Comment by gm119** [comment]
> Would we want this to cover RMCE target sites in the genome?

I made a separate 'RMCE target' term for the RMCE case  (FBrf0231034 Fig 10b and 10c) where a chunk of sequence is surrounded by **2** recombinase/integrase sites and can be 'swapped' with sequence from a compatible donor  - This separate term is one of the two in: https://github.com/FlyBase/flybase-controlled-vocabulary/issues/33

This "docking site" terms is meant to cover just FBrf0231034 fig10a (where there is a single integrase site).

I think that the current definition is what is wanted - I just checked Bloomington, and they have these two things as two separate lists on their https://bdsc.indiana.edu/stocks/phic31/index.html page:

- "Single attP-bearing insertions for standard integration" (this is what docking site is meant to represent), which goes to https://bdsc.indiana.edu/stocks/phic31/phic31_attp.html

- "Double attP-bearing insertions for integration via Recombination-Mediated Cassette Exchange (RMCE)", which goes to https://bdsc.indiana.edu/stocks/phic31/phic31_rmce.html

So I think its OK as is.

**Comment by gm119** [comment]
I think maybe a solution to this one is to change the name of this term from 'docking site' to 'docking element' - rather than being used for the single integrase target site itself, its supposed to be used to describe a transgenic construct/inserted DNA segment that is designed to be used to insert things into the genome, due to it _containing_ the single integrase target site.

So I think maybe the following would work, as it makes it clearer its referring to the whole inserted element, not just the target site:

[Term]
name: docking element
namespace: experimental_tool_descriptor
def: "A docking element is an element that has been introduced into a site in the genome to allow integration of DNA at a defined location; this neutralizes the problem of position effects that are seen with non-specific insertion techniques such as transposable-element-mediated transgenesis. A docking element contains a single target site for an integrase, allowing subsequent integration of DNA into this site from a donor element via integrase mediated recombination. The docking element in the genome typically contains the 'attB' site and the donor plasmid contains the 'attP' site, since this directionality gives higher integration rates compared to the alternative combination where the 'attB' site is integrated into the genome. A docking element insertion is typically selected to be 'benign' (that is it does not result in disruption of an endogenous locus) and to show a high rate of integration in the presence of integrase." [FBC:GM, PMID:11359900, PMID:12563279, FlyBase:FBrf0194996, FlyBase:FBrf0192974]
is_a: FBcv:0005075 ! genome engineering tool
synonym: landing site
synonym: docking site

_(if we start being able to use 'part_of' in FBcv, then we could also add

has_part: FBcv:0005079 ! integrase target site

but for now we should leave that out)_

**Comment by Clare72** [comment]
Ok, site -> element makes sense.

I still think the name sounds quite general, when the definition is more specific. I would favour a more descriptive name, such as 'single integrase site docking element', as I am not sure how many people thoroughly read the definitions.

NB. This definition does not exclude elements with RMCE recombinase sites as well as a single integrase site, but any element with multiple integrase sites will be excluded (not a problem, just something to be aware of).

I might also add a comment to clarify what is included/excluded based on FBrf0231034 Fig 10.
Comment: "This includes any element containing a single site for integrase-mediated integration, as in FBrf0231034 Fig 10a, but not elements with mulitple integrase sites, as in FBrf0231034 Fig 10b (see <reference to RMCE target term>). Elements with sites for recombinase-mediated exchange (as in FBrf0231034 Fig 10c) are only included if they additionally carry exactly one integrase site for integrase-mediated integration."

**Comment by gm119** [comment]
I like the comment.

Could we add 'single integrase site docking element' as a synonym, and keep 'docking element' as the valid name. I don't think the community will know what a 'single integrase site docking element' is without reading the definition (so I wouldn't really want that to be the valid name!), but I think they will know what a 'docking element' is as it is the kind of language already used in the community.
