### ISSUE TITLE
split recombinase

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#40]
new term request::

[Term]
name: split recombinase
namespace: experimental_tool_descriptor
def: "Catalytically inactive fragment of a recombinase. A functional recombinase can be reconstituted when complementary split recombinase fragments are brought together in vivo by fusing the fragments to peptides that physically interact." [FBC:GM]
is_a: FBcv:0005051 ! split system component

**Comment by Clare72** [comment]
Based on definitions, this should be a subclass of 'split reporter enzyme':
>Catalytically inactive fragment of an enzyme. A functional enzyme can be reconstituted when complementary split enzyme fragments are brought together in vivo by fusing the fragments to peptides that physically interact, permitting the study of protein-protein interactions.

However, I think that maybe the 'reporter' part of 'split reporter enzyme' has meaning that has not made it into the definition. Do we need to add something about 'split reporter enzyme' being used for detection?

**Comment by gm119** [comment]
you are quite right about 'split reporter enzyme'.
I incorporated some info from the 'reporter enzyme' term, how is this:

def: "Catalytically inactive fragment of a reporter enzyme, an enzyme whose activity can be used to detect the presence of that protein product. A functional reporter enzyme can be reconstituted when complementary split reporter enzyme fragments are brought together in vivo by fusing the fragments to peptides that physically interact, permitting the study of protein-protein interactions." [FBC:GM, PMID:9237989]

**Comment by Clare72** [comment]
I am tempted to borrow a bit more from 'reporter enzyme', otherwise saying 'that protein product' sounds a bit awkward. How about:
>Sequence that forms all or part of the protein product encoded by a transgenic locus or modified endogenous locus and that encodes a catalytically inactive fragment of an enzyme whose activity can be used to detect the presence of that protein product when complementary split reporter enzyme fragments are brought together in vivo. Fragments may be brought together when fused to peptides that physically interact, permitting the study of protein-protein interactions.

**Comment by gm119** [comment]
thats fine
