### ISSUE TITLE
'binding tool' terms

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#43]
New terms to use with experimental tools that specifically bind to something, to go under 'experimental tool descriptor' branch of FBcv

**A. summary of tree:**

       specific binding tool
	       purification tag
	       antibody
		      nanobody
	       epitope tag
	       conditional specific binding tool
		      light-regulated specific binding tool
		      small molecule-regulated specific binding tool
		      temperature-regulated specific binding tool

**B. New CV terms requested:**

[Term]
id: FBcv:NEW
name: specific binding tool
namespace: experimental_tool_descriptor
def: "Sequence that has a property that allows specific binding to another macromolecule." [FBC:GM]
is_a: FBcv:0005001 ! experimental tool descriptor

[Term]
id: FBcv:NEW
name: conditional specific binding tool
namespace: experimental_tool_descriptor
def: "Sequence that has a property that allows specific binding to another macromolecule, where this property can be regulated in response to a particular stimulus." [FBC:GM]
is_a: FBcv:NEW ! specific binding tool

[Term]
id: FBcv:NEW
name: light-regulated specific binding tool
namespace: experimental_tool_descriptor
def: "Sequence that has a property that allows specific binding to another macromolecule, where this property can be regulated by irradiation with a pulse of light." [FBC:GM]
is_a: FBcv:NEW ! specific binding tool

[Term]
id: FBcv:NEW
name: small molecule-regulated specific binding tool
namespace: experimental_tool_descriptor
def: "Sequence that has a property that allows specific binding to another macromolecule, where this property can be regulated by binding to a small molecule, such as an ion or ligand." [FBC:GM]
is_a: FBcv:NEW ! specific binding tool

[Term]
id: FBcv:NEW
name: temperature-regulated specific binding tool
namespace: experimental_tool_descriptor
def: "Sequence that has a property that allows specific binding to another macromolecule, where this property can be regulated by temperature." [FBC:GM]
is_a: FBcv:NEW ! specific binding tool

[Term]
name: antibody
namespace: experimental_tool_descriptor
def: ??see comment below??
is_a: FBcv:NEW ! specific binding tool

the experimental condition ontology term XCO:0000194 (https://www.ebi.ac.uk/ols/ontologies/xco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FXCO_0000194) has the following definition which I think would work, but not sure the correct way to refer to this ontology term and put in the definition:

An immunoglobulin molecule having a specific amino acid sequence that gives each antibody the ability to adhere to and interact only with the antigen that induced its synthesis and with molecules containing structures similar to that antigen. An antigen is any substance capable of inducing a specific immune response, including but not limited to toxins, bacterial proteins and viruses. [ Miller-Keane:Miller-Keane_Encyclopedia_and_Dictionary_of_Medicine_Nursing_and_Allied_Health--7th_Ed ]

[Term]
name: nanobody
def: "Antigen-binding variable domain of a camelid heavy chain antibody; a single domain antibody fragment that binds a specific antigen." [FBC:GM, PMID:16095608]
is_a: FBcv:NEW ! antibody

C. edits for existing terms.

The following terms already exist in FBcv, but need an edit to place them under the new 'specific binding tool' term.

a.

id: FBcv:0005036
name: purification tag

this is currently under the tree as:

is_a: FBcv:0005001 ! experimental tool descriptor

can it be moved so that it is under 'specific binding tool' i.e. move to:

is_a: FBcv:NEW ! specific binding tool

b. 

id: FBcv:0005021
name: epitope tag

this is currently listed as a child of:
is_a: FBcv:0005004 ! protein detection tool

this is fine, but can the following relationship also be added:

is_a: FBcv:NEW ! specific binding tool

**Comment by gm119** [comment]
added conditional specific bindong tool and 3 child terms

**Comment by Clare72** [comment]
I don't think we can add 'purification tag' as a child as its definition does not say that purification must occur through binding and I think there are other ways to use purification tags, e.g. making something a lot bigger to separate it on a gel.

Epitope tag defines 'epitope' as a binding site, so we can make this a child.

**Comment by gm119** [comment]
that makes, sense, fine with me

**Comment by Clare72** [comment]
'antibody' and 'nanobody' still to do

**Comment by gm119** [comment]
(corrected pmid for nanobody)

**Comment by gm119** [comment]
definition of nanobody needs updating - folks are now making artificial antibodies so they are not all camellid derived any more

**Comment by gm119** [comment]
I was thinking of marking this ticket as closed and making a new one for the antibody and child terms - is that OK ?
