### ISSUE TITLE
fbcv/dpo.owl resolves to SourceForge

### ISSUE THREAD

**Issue by cmungall** [FlyBase/flybase-controlled-vocabulary#6]
Related to: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/18

Still not 100% sure of the correct PURL to use

http://purl.obolibrary.org/obo/fbcv/dpo.owl still resolves to sourceforge - is this intended?

The ontology URI in the file is:

```
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/dpo.owl">
```

these should match

**Comment by mmc46** [comment]
I still haven't moved the code across from Sourceforge to GitHub. It will be done in the next few weeks. 

I'll make sure the PURL is the correct one, though still pointing to SourceForge for now. 

Marta

**Comment by mmc46** [comment]
Hi Chris,

I’ve moved the repository, but can’t find that purl to update. Together with others like

http://purl.obolibrary.org/obo/fbbt/fbbt-simple.obo <http://purl.obolibrary.org/obo/fbbt/fbbt-simple.obo>

which don’t show up on 

https://purl.oclc.org/docs/index.html <https://purl.oclc.org/docs/index.html>

**Comment by mmc46** [comment]
The purl http://purl.obolibrary.org/obo/fbcv/dpo.owl <http://purl.obolibrary.org/obo/fbcv/dpo.owl> 
now points to GitHub.

**Comment by cmungall** [comment]
Hurrah!

**Comment by cmungall** [comment]
Can you post any request relating to purls here, someone will likely 
take care of it before me
https://github.com/OBOFoundry/OBOFoundry.github.io/issues
