### ISSUE TITLE
Make sure no "No definition" cases left

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#60]
Currently, there are 32 definitions that say "No description"

```
[Term]
id: FBcv:0000527
name: diethyl sulfate
namespace: origin_of_mutation
def: "No description" [CHEBI:34699]
synonym: "DES" RELATED []
synonym: "mutation induced by diethyl sulfate exposure" EXACT []
is_a: FBcv:0000526 ! alkylating agent
```
The reason for that is that Chebi does not have definitions for quite a few terms, see for example this case here:

https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_34699

What do you want to happen in this case?

**Comment by matentzn** [comment]
(currently, a "No description" definition is created, but we could create a "See CHEBI:0001" description instead.. even if it has none..

**Comment by dosumis** [comment]
Wouldn't worry too much  about  these.   Perhaps just keep blank?  Clare's call.

**Comment by Clare72** [comment]
I wouldn't worry about this, the chemical terms are pretty self-explanatory. Curators can google the names to find out what they are, I don't think there will be much ambiguity.

**Comment by matentzn** [comment]
So currently in these cases we say: "No description". So @Clare72 do you want to either 
- delete these cases from the edit file (no work for me)
- Add a string like "see CHEBI:X"
- Leave the "No description" (as soon as they add one at Chebi, it will appear correctly)
- Remove definitions when we cant find a chebi definition dynamically (most work for me, but still less than 20 min)

**Comment by Clare72** [comment]
Leave the "No description" (as soon as they add one at Chebi, it will appear correctly)
