### ISSUE TITLE
Remove dates from edit file

### ISSUE THREAD

**Issue by Clare72** [FlyBase/flybase-controlled-vocabulary#62]
Remove dates from edit file (currently still needed to generate correct dates in artefacts).

**Comment by dosumis** [comment]
I don't think we need to add them back.  We just need to make sure all release files have the date in header `data-version:` tag.  This should be automatically added during ODK release - If not our PURL versioning will be screwed, as this is used for version-iri generation during conversion to OWL.

**Comment by matentzn** [comment]
The ODK standard for the version string is this:

```
data-version: fbcv/releases/2019-07-11/fbcv-simple.owl
```

should we warm up FlyBase to this new way of version string, or leave their old:

```
data-version:2019-07-11
```

**Comment by Clare72** [comment]
Leave it for now, if nothing else causes the checks to fail then we can experiment

**Comment by matentzn** [comment]
I wont change it now; :D hahah just passing the time while the build is running.

**Comment by dosumis** [comment]
> The ODK standard for the version string is this:

> ```
> data-version: fbcv/releases/2019-07-11/fbcv-simple.owl
> ```

> should we warm up FlyBase to this new way of version string, or leave their old:

> ```
> data-version:2019-07-11
> ```

Are you sure about that being the ODK standard version vs something currently munged by the pipeline?  I think we need to review this (in and ODK call?) and make sure we're not screwing up the resolution of of version-iris - particularly for the OWL files.  

As I understand it, the released fbcv.obo will be the -simple version, but that should definitely have the plain:

``yaml
data-version: 2019-07-11
ontology: fbcv
```

(Note to self: I need to understand the partitioning better between `data-version:` and `ontology:` tags and how the two produce the version IRI.)
