### ISSUE TITLE
Revise Flybase ontology release mechanism

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#66]
FBCV used to have this system that releases were placed in parallel into the "releases" sub-directory. The question is whether we want to continue to do that, or wether we go with the "normal" way of keeping the latest version on the top level, and creating proper github releases (to which the version iris would point). I am not bothered either way. Both of them require modifications to the existing mechanisms.

**Comment by dosumis** [comment]
I think we need to follow the standard route on this.  AFAIK, it's the only way to get version IRIs to resolved if releasing as GitHub tags.

**Comment by matentzn** [comment]
Another thought: I think I would prefer if we have a "current" release on Github, to which the normal, non-versioned PURLs point, rather than simply pointing to the master branch. This gives us more control; on the other hand, it also makes more work for us.. Do you have an opinion @dosumis ?

**Comment by matentzn** [comment]
Ok, on second thought, adding current releases probably is an unncessary complexity for the maintainance of the flybase ontologies for the following reasons:
1) The largest flybase ontology, fbbt, is only 36MB in size - it will never scratch the GitHUb filesize limit
2) Most ontologies do not do current tagged releases
3) Versioned tagged release, the OBO standard, of course, have to be done and work (we double checked it now; they resolve correctly for Clares past releases).
