### ISSUE TITLE
Verify one last time that the release is ok

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#67]
Should be after all the work we put into it! :)

diff this: 
https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/fbcv-simple.obo
with
https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/fbcv-odk/fbcv-simple.obo

at least, maybe one last glance at the flybase release. Then you can merge the branch.

This should really be good enough by now, but let me know anything problematic.

**Comment by Clare72** [comment]
-simple and -flybase look good to me.
Does it matter that it still says "All checks have failed"?

**Comment by matentzn** [comment]
No, it does not; but you can try to fix them if you want: Some minor QC errors:

https://travis-ci.com/FlyBase/flybase-controlled-vocabulary/builds/120771298

**Comment by matentzn** [comment]
Perfect you fixed it. The other error can be ifmgbkted, will take care of that.

**Comment by matentzn** [comment]
Ignored
