### ISSUE TITLE
Make sure that the robot_diff command compares with LAST PURL

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#69]
Right now can be 

SIMPLE_PURL =	http://purl.obolibrary.org/obo/fbdv/fbdv-simple.obo

Do this for all four ontologies:

- [ ] fbdv
- [ ] fbcv
- [ ] fbbt
- [ ] dpo

**Comment by Clare72** [comment]
robot_simple_diff.txt files seem to be comparing the correct files now, so closing this issue
