### ISSUE TITLE
Loss of non-redundant axiom in fbcv.obo

### ISSUE THREAD

**Issue by Clare72** [FlyBase/flybase-controlled-vocabulary#76]
We are losing this relationship from FBcv:0000525 'chemical' in fbcv.obo and fbcv.owl:
>is_a: FBcv:0000452 ! origin of mutation

This results in chemical terms falling under owl:Thing rather than 'origin of mutation' in the fbcv hierarchy.
This also affects fbcv-full, but not other files.

In fbcv-edit.obo:
>[Term]
id: FBcv:0000525
name: chemical
namespace: origin_of_mutation
def: "$sub_CHEBI:24431" [CHEBI:24431]
synonym: "mutation induced by chemical exposure" EXACT []
is_a: FBcv:0000452 ! origin of mutation

In fbcv.obo:
>[Term]
id: FBcv:0000525
name: chemical
namespace: origin_of_mutation
def: "A chemical entity is a physical entity of interest in chemistry including molecular entities, parts thereof, and chemical substances." [CHEBI:24431]
synonym: "mutation induced by chemical exposure" EXACT []
is_a: CHEBI:24431 ! chemical entity

In both files chemical entity has:
>equivalent_to: FBcv:0000525 ! chemical

**Comment by matentzn** [comment]
This unboxed a scary can of worms.. Hahha. I think I found a workaround, but we this will get rid of redundancy stripping..

**Comment by dosumis** [comment]
Sounds familiar. Thought we'd fixed this a couple of months back.   We can live with redundancy in the full release.

**Comment by matentzn** [comment]
This was a problem with OORT. But this here is something really weird. It is caused merely by running reduce (no filter/remove stuff of any kind).
