### ISSUE TITLE
fbcv-full cannot be reduced

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#77]
The full profile of FBCV involves a step where redundant axioms are stripped out. Unfortunately, much more than just redundant axioms are stripped, and I assume this is due to equivalent class cycles we need to investigate. the current workaround is the NOT do any redundancy stripping: fbcv.Makefile

```
# For some reason, using reduce just does not work on FBCV this is a workaround, but it needs some figuring out..

$(ONT)-full.owl: $(SRC) $(OTHER_SRC)
	$(ROBOT) merge --input $(SRC) \
		reason --reasoner ELK --equivalent-classes-allowed asserted-only \
		relax \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --annotation oboInOwl:date "$(OBODATE)" --output tmp/full.owl

```

**Comment by gouttegd** [comment]
Whatever the cause of the problem was, FBcv is no longer affected by it: I’ve removed the custom rule above as part of the switch to base merging (#198), and the resulting fbcv-full didn’t lose anything more than the redundant axioms that were supposed to be removed.
