### ISSUE TITLE
MeSH term links broken

### ISSUE THREAD

**Issue by Clare72** [FlyBase/flybase-controlled-vocabulary#87]
Old links to Mesh terms no longer working (many have '2011' in URL) - replace these with http://id.nlm.nih.gov/mesh/M0029016 style links (to concepts)

**Comment by Clare72** [comment]
Looks like xrefs on def don't make it into FB anyway. Only primary annotations are shown (as 'MeSH:XXXXXXX') and these don't link out.

**Comment by Clare72** [comment]
'MeSH:XXXXXXX' do work as linkouts from OLS! - maybe convert all MeSH links to this format

**Comment by matentzn** [comment]
Standardising these links is a great idea.. It really is a shame that curie syntax is the preferred way to represent xrefs :( -> a proper linkout would have been better. I think a quick regex string replace thing with Atom should do the trick.
