### ISSUE TITLE
new antibody experimental tool terms

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#93]
New FBcv experimental tool terms for antibody and child terms

**A. summary of tree:**

       specific binding tool
	       antibody
		       engineered antibody
			       nanobody 
			       single-chain variable fragment antibody

**B. New terms requested:**

[Term]
id: FBcv:NEW
name: antibody
namespace: experimental_tool_descriptor
def: ??see comment below??
subset: common_tool_use
is_a: FBcv:0007029 ! specific binding tool

the experimental condition ontology term XCO:0000194 (https://www.ebi.ac.uk/ols/ontologies/xco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FXCO_0000194) has the following definition which I think would work, but not sure the correct way to refer to this ontology term and put in the definition:

An immunoglobulin molecule having a specific amino acid sequence that gives each antibody the ability to adhere to and interact only with the antigen that induced its synthesis and with molecules containing structures similar to that antigen. An antigen is any substance capable of inducing a specific immune response, including but not limited to toxins, bacterial proteins and viruses. [ Miller-Keane:Miller-Keane_Encyclopedia_and_Dictionary_of_Medicine_Nursing_and_Allied_Health--7th_Ed ]

[Term]
id: FBcv:NEW
name: engineered antibody
namespace: experimental_tool_descriptor
def: "An antibody whose domain architecture has been engineered in vitro. An engineered antibody typically contains only a subset of the domains found in a naturally occurring antibody. In some cases, domains that are normally found in different chains of a naturally occurring antibody are synthesized as a single fusion protein." [FBC:GM]
is_a: FBcv:NEW ! antibody

[Term]
id: FBcv:NEW
name: nanobody
namespace: experimental_tool_descriptor
def: "An engineered antibody consisting of the antigen-binding variable domain (VHH domain) of a camelid single-domain heavy chain antibody (HCab)." [FBC:GM, PMID:8502296, PMID:9323027, PMID:22886243]
is_a: FBcv:NEW ! engineered antibody

id: FBcv:NEW
name: single-chain variable fragment antibody
namespace: experimental_tool_descriptor
def: "An engineered antibody consisting of the heavy (VH) and light (VL) chains of an immunoglobulin, separated by a short flexible linker peptide and expressed as a single fusion protein." [FBC:GM, PMID:3045807]
is_a: FBcv:NEW ! engineered antibody
synonym: "scFv antibody" RELATED [FBC:GM]
synonym: "sFv antibody" RELATED [FBC:GM]

**Comment by Clare72** [comment]
I think it is best to remove 'only' from the definition of 'antibody' as this is overly restrictive when taken literally.

**Comment by gm119** [comment]
I agree !
